In [1]:
import pandas as pd

In [6]:
pd.read_csv("20_24평균기온.txt", skiprows = 6)

               년월   지점  평균기온(℃)  평균최저기온(℃)  평균최고기온(℃)
0   \t\t\t2020-01  156      3.6        NaN        NaN
1   \t\t\t2020-02  156      2.4        NaN        NaN
2   \t\t\t2020-03  156      1.5        NaN        NaN
3   \t\t\t2020-04  156     -1.9        NaN        NaN
4   \t\t\t2020-05  156      0.1        NaN        NaN
5   \t\t\t2020-06  156      0.9        NaN        NaN
6   \t\t\t2020-07  156     -2.5        NaN        NaN
7   \t\t\t2020-08  156      1.1        NaN        NaN
8   \t\t\t2020-09  156     -0.9        NaN        NaN
9   \t\t\t2020-10  156     -0.4        NaN        NaN
10  \t\t\t2020-11  156      0.9        NaN        NaN
11  \t\t\t2020-12  156     -0.5        NaN        NaN
12  \t\t\t2021-01  156      0.4        NaN        NaN
13  \t\t\t2021-02  156      2.2        NaN        NaN
14  \t\t\t2021-03  156      3.1        NaN        NaN
15  \t\t\t2021-04  156      1.5        NaN        NaN
16  \t\t\t2021-05  156     -0.3        NaN        NaN
17  \t\t\t2021-06  156      0.6        NaN        NaN
18  \t\t\t2021-07  156      1.1        NaN        NaN
19  \t\t\t2021-08  156     -0.7        NaN        NaN
20  \t\t\t2021-09  156      0.7        NaN        NaN
21  \t\t\t2021-10  156      1.1        NaN        NaN
22  \t\t\t2021-11  156      0.6        NaN        NaN
23  \t\t\t2021-12  156      0.9        NaN        NaN
24  \t\t\t2022-01  156      0.6        NaN        NaN
25  \t\t\t2022-02  156     -1.1        NaN        NaN
26  \t\t\t2022-03  156      2.1        NaN        NaN
27  \t\t\t2022-04  156      2.1        NaN        NaN
28  \t\t\t2022-05  156      0.6        NaN        NaN
29  \t\t\t2022-06  156      1.1        NaN        NaN
30  \t\t\t2022-07  156      1.1        NaN        NaN
31  \t\t\t2022-08  156      0.4        NaN        NaN
32  \t\t\t2022-09  156      0.9        NaN        NaN
33  \t\t\t2022-10  156     -0.1        NaN        NaN
34  \t\t\t2022-11  156      2.2        NaN        NaN
35  \t\t\t2022-12  156     -2.1        NaN        NaN
36  \t\t\t2023-01  156      0.7        NaN        NaN
37  \t\t\t2023-02  156      1.3        NaN        NaN
38  \t\t\t2023-03  156      3.7        NaN        NaN
39  \t\t\t2023-04  156      1.3        NaN        NaN
40  \t\t\t2023-05  156      0.7        NaN        NaN
41  \t\t\t2023-06  156      0.7        NaN        NaN
42  \t\t\t2023-07  156      0.4        NaN        NaN
43  \t\t\t2023-08  156      0.8        NaN        NaN
44  \t\t\t2023-09  156      1.6        NaN        NaN
45  \t\t\t2023-10  156      0.5        NaN        NaN
46  \t\t\t2023-11  156      0.3        NaN        NaN
47  \t\t\t2023-12  156      1.6        NaN        NaN
48  \t\t\t2024-01  156      2.0        NaN        NaN
49  \t\t\t2024-02  156      3.2        NaN        NaN
50  \t\t\t2024-03  156      NaN        NaN        NaN

In [9]:
pd.read_csv("체감온도.txt", skiprows = 3)

             일자  기온(°C)  풍속(km/h)  체감온도(°C)
0    2020-01-01    -4.8      14.8     -10.3
1    2020-01-02     1.4       4.7       0.1
2    2020-01-03     1.9       6.1       0.1
3    2020-01-04    -1.0       4.7      -2.6
4    2020-01-05     1.0       4.7      -0.3
..          ...     ...       ...       ...
777  2024-03-01    -3.6       9.4      -7.4
778  2024-03-02    -5.1       9.7      -9.3
779  2024-03-03     1.9       5.4       0.4
780  2024-03-04     3.3       3.6       2.8
781  2024-03-05     5.2      19.1       1.4

[782 rows x 4 columns]